config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'main#index'
  mount Sidekiq::Web => '/sidekiq'

  resources :alarms, only: :create do
    member do
      patch :upvote
    end
  end
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  scope :latest, -> { order(upvotes: :desc, created_at: :desc) }

  before_save :load_ranking
  after_create :post_to_api

  def load_ranking
    # self.ranking = (created_at.to_i - Time.now.to_i) + upvotes.to_i
  end

  def upvote!
    update_column(:upvotes, upvotes.to_i + 1)
  end

  def post_to_api
    ApiServiceJob.perform_later(self.id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  def create
    @alarm = Alarm.new(alarm_params)
    if @alarm.valid?
      @alarm.save
      @alarms = Alarm.latest
    end
  end

  def upvote
    @alarm = Alarm.find(params[:id])
    @alarm.upvote!
  end

  protected

  def alarm_params
    params.require(:alarm).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @alarm = Alarm.new
    @alarms = Alarm.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alarms/_alarm.html.haml
.card.alarm-card
  .row
    .col-md-9
      = alarm.description.upcase
      %br/
      = link_to 'upvote', upvote_alarm_path(alarm), remote: true, method: :patch, class: 'badge badge-success'
    .col-md-3.alarm-timestamp
      = alarm.created_at.strftime('%m/%d %H:%M')
      %br/
      .votes-container{id: "#{alarm.id}_votes_container"}
        = render 'alarms/votes', alarm: alarm

app/views/alarms/_votes.html.haml
#{alarm.upvotes.to_i} votes so far

app/views/alarms/create.js.haml
:plain
  $('.alarms-container').html('#{escape_javascript(render(@alarms))}')
  $('#alarm_description').val('')

app/views/alarms/upvote.js.haml
:plain
  $('##{@alarm.id}_votes_container').html('#{escape_javascript(render('alarms/votes', alarm: @alarm))}')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Alarms
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .container-fluid
      .row
        .col-md-1
        .col-md-10
          = yield        
        .col-md-1

app/views/main/index.html.haml
%h1 Alarms

= form_for @alarm, remote: true do |f|
  .form-group
    = f.text_area :description, rows: 4, class: 'form-control', placeholder: 'Enter alarm text...'
  .form-group
    = f.submit 'Send', class: 'btn btn-info'

.alarms-container
  = render @alarms